config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root :to => 'home#index'

  get '/our-specialties', to: 'specialties#index', as: "specialties"
  get '/our-specialties/article', to: 'specialties#get_article', as: "get_specialty"
  get '/services', to: 'services#index', as: "services"
  get '/contact-us', to: 'contact#index', as: "contact"
  get '/enrollment-forms', to: 'enrollment#index', as: "enrollment"
  post '/contact/send_mail', to: 'contact#send_mail', as: "message"
  get '/about-us', to: 'about#index', as: "about"
  get '/340b', to: 'threeb#index', as: "assured"
  get '/pa', to: 'pa#index', as: "prior_auth"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
    @article = params[ :article ]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index
    if params[ "success" ]
      @contact_success = "true"
    end
  end

  def send_mail
    @first_name = params[ "first_name" ]
    @last_name = params[ "last_name" ]
    @city = params[ "city" ]
    @state = params[ "state" ]
    @phone = params[ "phone" ]
    @email = params[ "email" ]
    @message = params[ "message" ]
    ContactMailer.new_contact( @first_name, @last_name, @city, @state, @phone, @email, @message ).deliver_now
    redirect_to controller: 'contact', action: 'index', success: 'true'
  end
end

app/controllers/enrollment_controller.rb
class EnrollmentController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/pa_controller.rb
class PaController < ApplicationController
  def index
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  def index
  end
end

app/controllers/specialties_controller.rb
class SpecialtiesController < ApplicationController
  def index
    if params[ "article" ]
      @article = params[ "article" ]
    end
  end

  def get_article
    @article = params[ "article" ]
    render partial: @article, layout: false, locals: { article: @article }
  end
end

app/controllers/threeb_controller.rb
class ThreebController < ApplicationController
  def index
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def active_class(link_path)
    url = link_path.split( "\">" )[ 1 ][ 0..-5 ]

    current_page?( url ) ? "active" : ""
  end
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/enrollment_helper.rb
module EnrollmentHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pa_helper.rb
module PaHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/specialties_helper.rb
module SpecialtiesHelper
end

app/helpers/threeb_helper.rb
module ThreebHelper
end

app/views/about/index.html.erb
<%= stylesheet_link_tag    '/css/reset.css' %>
<%= javascript_include_tag '/js/modernizr.js' %>

<%= render "layouts/mini_nav" %>

<%= render "layouts/nav" %>

<%= render @article %>

<%= javascript_include_tag '/js/main.js' %>

<%= render "layouts/partner_logos" %>

<%= render "layouts/footer" %>

app/views/layouts/_mini_nav.html.erb
<div class="container-fluid hidden-xs hidden-sm">
  <div class="col-md-12">
    <ul class="top_nav">
      <li><a href="#">Provider Portal</a></li>
      <li><a href="#">Patient Portal</a></li>
      <li><%= link_to "Enrollment Forms", enrollment_path %></li>
    </ul>
  </div>
</div>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default ">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#my-navbar-collapse">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
            <div class="navbar-brand">
                <%= link_to root_path do %>
                  <%= image_tag "logo_color.png", alt: "QuickRX", class: "logo_img" %>
                <% end %>
            </div>
        </div>
        <div class="collapse navbar-collapse" id="my-navbar-collapse">
            <ul id="nav" class="nav navbar-nav navbar-right">
                <li><%= link_to "HOME", root_path, class: active_class( link_to root_url ) %></li>

                <li class="dropdown">
                    <%= link_to "ABOUT US", { :controller => "about", :action => "index", :article => "timeline" }, class: "dropdown-toggle #{ active_class( link_to about_url ) }" %>
                    <ul class="dropdown-menu multi-column columns-2">
                        <div class="row">
                            <div class="container-fluid">
                                <ul class="multi-column-dropdown">
                                  <li><%= link_to "HISTORY", { :controller => "about", :action => "index", :article => "timeline" } %></li>
                                	<li><a href="#">URAC ACCREDITATION</a></li>
                                	<li><a href="#">OUR EXECUTIVE TEAM</a></li>
                                  <li><a href="#">LOCATIONS WE SERVICE</a></li>
                                </ul>
                            </div>
                        </div>
                    </ul>
                </li>

                <li class="dropdown">
                    <%= link_to "OUR SPECIALTIES", { :controller => "specialties", :action => "index", :article => "it" }, class: "dropdown-toggle #{ active_class( link_to specialties_url ) }" %>
                    <ul class="dropdown-menu multi-column columns-2">
                        <div class="row">
                            <div class="container-fluid">
                                <ul class="multi-column-dropdown">
                                    <li><%= link_to "INFUSION THERAPY", {:controller => "specialties", :action => "index", :article => "it" }%></li>
                                    <li><%= link_to "HIV", {:controller => "specialties", :action => "index", :article => "hiv" }%></li>
                                    <li><%= link_to "MULTIPLE SCLEROSIS", {:controller => "specialties", :action => "index", :article => "ms" }%></li>
                                    <li><%= link_to "HEPATITIS C", {:controller => "specialties", :action => "index", :article => "hepc" }%></li>
                                    <li><%= link_to "HEPATITIS B", {:controller => "specialties", :action => "index", :article => "hepb" }%></li>
                                    <li><%= link_to "GASTROENTEROLOGY", {:controller => "specialties", :action => "index", :article => "gastro" }%></li>
                                    <li><%= link_to "IMMUNODEFICIENCY", {:controller => "specialties", :action => "index", :article => "immuno" }%></li>
                                    <li><%= link_to "RHEUMATOID ARTHRITIS", {:controller => "specialties", :action => "index", :article => "ra" }%></li>
                                    <li><%= link_to "HUNTINGTONS DISEASE", {:controller => "specialties", :action => "index", :article => "hd" }%></li>
                                    <li><%= link_to "ECZEMA", {:controller => "specialties", :action => "index", :article => "eczema" }%></li>
                                    <li><%= link_to "DEEP VEIN THROMBOSIS", {:controller => "specialties", :action => "index", :article => "dvt" }%></li>
                                </ul>
                            </div>
                        </div>
                    </ul>
                </li>
                <li class="dropdown">
                    <%= link_to "SERVICES", services_path, class: "dropdown-toggle #{ active_class( link_to services_url ) }" %>
                    <ul class="dropdown-menu">
                        <li><a href="#">EDUCATION</a></li>
                        <li><a href="#">FINANCIAL ASSISTANCE</a></li>
                        <li><a href="#">PRIOR AUTHORIZATION</a></li>
                        <li class="dropdown">
                          <a href="#">TECHNOLOGY</a>
                            <ul class="dropdown-menu">
                              <li><a href="#">SMS TEXTING</a></li>
                              <li><a href="#">PATIENT PORTAL</a></li>
                              <li><a href="#">PHYSICIAN PORTAL</a></li>
                              <li><a href="#">ADHERENCE PROGRAM</a></li>
                            </ul>
                        </li>
                    </ul>
                </li>

                <li><a href="http://340bassured.com" target="_blank">340B</a></li>

                <li><%= link_to "CONTACT US", contact_path, class: active_class( link_to contact_url ) %></li>
            </ul>
        </div>
    </div>
</nav>

<script type="text/javascript">
  $('.navbar .dropdown').hover(function() {
      $(this).find('.dropdown-menu').first().stop(true, true).delay(250).slideDown();
  }, function() {
      $(this).find('.dropdown-menu').first().stop(true, true).delay(100).slideUp()
  });
</script>

app/views/specialties/_dvt.html.erb
<div class="row">
    <p class="article-no-display">#<%= @article %> .icon</p>
    <div class="col-lg-4 col-md-3 col-sm-7 ">
        <div class="profile-box">
            <%= image_tag "card.png", width: "100%" %>
        </div>
    </div>
    <div class="col-lg-4 col-md-7 col-sm-5  pl-50">
        <h1>DEEP VEIN THROMBOSIS</h1>
        <br>

        <h4>What is Deep Vein Thrombosis?</h4>
        <p>Deep vein thrombosis (DVT) is a condition that forms blood clots in deep veins of the body.</p>

        <p><b>Where do DVT's form?</b></p>
        <p>DVT most commonly occurs in the legs, with 77% of patients experiencing DVT in only one leg and 12% of patients having blood clots in both legs. Very rarely do patients develop blood clots in other areas such as arms, neck, and pelvis. Deep vein thrombosis may cause pain or swelling in the leg but may also appear with minimal to no symptoms. If a blood clot breaks through the vein, it may travel to the lungs and cause a blockage of blood flow thus putting the patient at possible risk of a pulmonary embolism. DVT is usually resulting from limited blood circulation due to certain medications, surgery, and minimal movement.</p>

        <p><b>Treatment:</b></p>
        <p>DVT is a treatable condition with many different treatments and medication introduced. Some DVT treatments include clot busters (drugs administered through an IV to break up blood clots) and filters (vena cava filters prevent blood clots from traveling to your lungs). Other treatments such as blood thinners are given to patients to prevent blood clots initially. Drugs such as Warfarin (blood thinner) may cause patients to bleed excessively, and symptoms may include joint pain, severe headaches or stomach aches, and dizziness or weakness.
          <br>
          Specialty DVT medications that are used in DVT treatments include:
          <ul>
            <li>Arixtra®</li>
            <li>Fragmin®</li>
            <li>Lovenox®</li>
          </ul>
        </p>

        <p><b>For all inquires about deep vein thrombosis, DVT treatments, and various other medical conditions <%= link_to "contact", contact_path %> Quick RX’s expert team!</b></p>
        <%= link_to "Download A Referral Form", enrollment_path, class: "btn btn-default btnsubmit enrollment-trick" %>
    </div>
</div>

app/views/specialties/_eczema.html.erb
<div class="row">
    <p class="article-no-display">#<%= @article %> .icon</p>
    <div class="col-lg-4 col-md-3 col-sm-7 ">
        <div class="profile-box">
            <%= image_tag "card.png", width: "100%" %>
        </div>
    </div>
    <div class="col-lg-4 col-md-7 col-sm-5  pl-50">
        <h1>ECZEMA</h1>
        <br>

        <h4>What is Eczema?</h4>
        <p>
          Eczema, also referred to as Dermatitis, is a group of chronic skin conditions that can affect all ages. Eczema can cause the skin to become inflamed and itchy.  Dermatitis is brought on by a skin reaction. When Dermatitis becomes worse it is referred to as a “flare up”. There are many different types of eczema:
        </p>

        <ul>
          <li><b>Atopic Dermatitis-</b> the most common form of eczema. The Atopic Dermatitis eczema is caused by a skin reaction that leads to itching and inflammation. Atopic Dermatitis is common in infants. </li>
          <br>
          <li><b>Contact Dermatitis-</b> a form of eczema that causes red or inflamed skin due to direct contact with an irritant such as tight clothing.</li>
          <br>
          <li><b>Dyshidrotic Dermatitis-</b> also known as Dyshidrosis or Pompholyx, is eczema that causes blisters to develop on the hands and feet. The blisters caused by Pompholyx eczema are often filled with fluid and itchy. </li>
          <br>
          <li><b>Infantile Seborrhoeic-</b> this form of eczema, which is specific to newborns, is often called “Cradle Cap”. Infantile seborrhoeic dermatitis causes white or yellow scales to develop on the scalp which crust and flake off.</li>
          <br>
          <li><b>Adult Seborrhoeic-</b> Seborrhoeic Dermatitis for adults first develops as dandruff which if left unchecked eventually becomes itchy and scaly skin that can be of a yellow color. Adult Seborrhoeic Dermatitis can also affect the eyebrows, sides of the nose, and behind ears.</li>
          <br>
          <li><b>Asteatotic-</b> this form of dermatitis affects people who suffer from extremely dry skin. The dry skin of those who suffer from Asteatotic eczema often becomes abnormally dry, itchy, and cracked. Not heavily moisturizing the skin leads to flare ups </li>
          <br>
          <li><b>Varicose-</b> Varicose eczema is also known as Venous or Stasis Dermatitis. Stasis eczema or gravitational eczema is caused by fluid build-up which affects the lower legs.</li>
          <br>
          <li><b>Nummular Eczema-</b> also known as discoid eczema features ovular or coin shaped lesions on the skin. This form of eczema will sometimes occur after an injury. Nummular eczema sores are known to be itchy, ooze, and develop crusting.</li>
          <br>
        </ul>

        <h4>What are the symptoms of Dermatitis?</h4>

        <ul>
          <li>Allergies to mold, dust, pollen, and various etc.</li>
          <li>Cold and dry air can cause an eczema flare up</li>
          <li>An increase in temperature</li>
          <li>Excessive sweating</li>
          <li>Contact with irritants such as cleaning fluids</li>
          <li>Emotional stress</li>
          <li>Frequent hot baths and showers</li>
          <li>Sudden changes in temperature</li>
        </ul>

        <br>

        <h4>How do you get eczema?</h4>

        <p>Children are likely to develop dermatitis if their parents or other close family members have also suffered from the skin condition. Different factors, discussed in the symptoms section, can also cause a sudden outbreak of eczema.</p>


        <h4>Is it contagious?</h4>

        <p>Eczema is not contagious. Eczema cannot be transferred from one person to another through the exchange of bodily fluids, air, touch, etc.</p>


        <h4>Are there possible complications?</h4>

        <p>Scratching an eczema affected skin site can cause cuts. Damaged skin allows for infection by various viruses, fungi, or bacteria.</p>


        <h4>How is eczema diagnosed?</h4>

        <p>Dermatitis is diagnosed based on an examination by your doctor. Doctors will look at the condition of the skin and ask if you have a family history of eczema.</p>


        <h4>How is eczema treated?</h4>

        <p>There are many different treatments used to fight eczema. Some of which include:</p>

        <ul>
          <li><b>Meditation -</b> taking the time to meditate during the day can help those suffering from eczema</li>
          <br>
          <li><a href="https://www.dupixent.com/">DUPIXENT® (dupilumab)</a>- a new FDA certified treatment that has provided promising results to patients who have lived with dermatitis for years.</li>
        </ul>

        <br>

        <%= link_to "Download A Referral Form", enrollment_path, class: "btn btn-default btnsubmit enrollment-trick" %>
    </div>
</div>

app/views/specialties/_gastro.html.erb
<div class="row">
    <p class="article-no-display">#<%= @article %> .icon</p>
    <div class="col-lg-4 col-md-3 col-sm-7 ">
        <div class="profile-box">
            <%= image_tag "card.png", width: "100%" %>
        </div>
    </div>
    <div class="col-lg-4 col-md-7 col-sm-5  pl-50">
        <h1>GASTROENTEROLOGY</h1>
        <br>

        <h4>What is Gastroenterology?</h4>
        <p>Gastroenterology is a group of medicines dedicated to the treatment of digestive diseases. Gastroenterology focuses on treating problems with the digestive system which includes the stomach,  esophagus, small and large intestines (colon), liver, gallbladder, pancreas, bile ducts, and rectum. Specialists trained in depth in the use of Internal Medicine and are thus knowledgeable in treating diseases or disorders of the digestive system are called Gastroenterologist, Gastrointestinal doctors or GI. Gastroenterologists are frequently called when a patient is experiencing systems that lead to an unclear diagnosis or when a patient must take part in specialized diagnostic procedures.</p>

        <p><b>Transmission of Hepatitis C:</b></p>
        <p>The HCV disease is most commonly transmitted through the sharing of needles required for drug use. Hep C can also be transmitted, less commonly, through receiving a blood of organ donation. HCV is transmitted from mother to child during birth. Hep C can also be transmitted through sexual interaction with an infected person.</p>

        <p><b>So What Do GI's Treat?</b></p>
        <p>GIs are called upon to treat conditions such as but not limited to:
          <ul>
            <li>Abdominal pain</li>
            <li>Constipation</li>
            <li>Crohn’s disease</li>
            <li>Esophageal Reflux</li>
            <li>Gastritis</li>
            <li>Malabsorption</li>
            <li>Jaundice</li>
            <li>Liver disease</li>
            <li>Vomiting</li>
            <li>Ulcers</li>
            <li>Diarrhea</li>
            <li>Colon cancer</li>
            <li>Heartburn</li>
          </ul>
        </p>

        <p><b>Treatment:</b></p>
        <p>Medications used to treat diseases or disorders of the digestive system include:
          <ul>
            <li>CIMZIA®</li>
            <li>HUMIRA®</li>
            <li>REMICADE®</li>
            <li>SIMPONI®</li>
            <li>STELARA®</li>
            <li>XIFAXAN</li>
            <li>ENTYVIO™</li>
          </ul>
        </p>

        <%= link_to "Download A Referral Form", enrollment_path, class: "btn btn-default btnsubmit enrollment-trick" %>
    </div>
</div>

app/views/specialties/_hd.html.erb
<div class="row">
    <p class="article-no-display">#<%= @article %> .icon</p>
    <div class="col-lg-4 col-md-3 col-sm-7 ">
        <div class="profile-box">
            <%= image_tag "card.png", width: "100%" %>
        </div>
    </div>
    <div class="col-lg-4 col-md-7 col-sm-5  pl-50">
        <h1>HUNTINGTONS DISEASE</h1>
        <br>

        <h4>What is Huntington’s disease?</h4>
        <p>Huntington’s disease (HD) is a neurodegenerative disease that results in the progressive breakdown of the brain’s nerve cells. As HD destroys nerve cells, it deteriorates a person’s physical and mental capabilities. The more the huntingtin or HTT gene sequence repeats in an individual’s genetic code the more present the disorder. Generally, those with Huntington’s disease develop symptoms between 30 and 40 years of age. When the disease emerges earlier in life, before the age of 20, the condition is called juvenile Huntington’s disease.
        </p>

        <h4>Who is at Risk?</h4>

        <p>
          Every child with a parent that carries the huntingtin gene is at risk of having Huntington’s disease. Huntington’s disease is a family disease due to the gene having a 50% chance of being passed on to a carrier’s child.
          <br>
          Huntington’s disease cannot be passed on by means outside of being a descendant of a carrier and thus is noncontagious.
        </p>

        <h4>What are the symptoms of Huntington’s disease?</h4>

        <p>
          <ol>
            <li>
              <b>Movement Disorders</b>
              <br>
              <ul>
                <li>Chorea - involuntary jerking or writhing movements</li>
                <li>Dystonia - involuntary muscle spasms, rigidity, or contracture</li>
                <li>Impaired posture and balance</li>
                <li>Difficulty with physically producing speech</li>
                <li>Difficulty swallowing</li>
              </ul>
            </li>
            <br>
            <li>
              <b>Cognitive Disorders</b>
              <br>
              <ul>
                <li>Difficulty prioritizing or focusing on tasks</li>
                <li>Perseveration - inappropriate recurrence of one thought, behavior, or action</li>
                <li>Lack of impulse control</li>
                <li>Sexual promiscuity</li>
                <li>Slowness in processing words</li>
                <li>Difficulty learning and understanding new information</li>
                <li>Lack of self-awareness </li>
              </ul>
            </li>
            <br>
            <li>
              <b>Psychiatric Disorders</b>
              <br>
              <ul>
                <li>Irritability</li>
                <li>Sadness</li>
                <li>Apathy</li>
                <li>Social withdrawal</li>
                <li>Insomnia</li>
                <li>Suicidal thoughts</li>
                <li>Obsessive-compulsive disorder</li>
                <li>Mania</li>
                <li>Bipolar disorder</li>
              </ul>
            </li>
          </ul>
        </ol>

        <h4>What are the Symptoms of Juvenile Huntington’s Disease?</h4>

        <ol>
          <li>
            <b>Behavioral changes</b>
            <ul>
              <li>Loss of learned skills (academic or physical)	</li>
              <li>Development of behavioral problems</li>
            </ul>
          </li>
          <br>
          <li>
            <b>Physical changes</b>
            <ul>
              <li>Dystonia - involuntary muscle spasms, rigidity, or contracture</li>
              <li>Deterioration of fine motor skills</li>
              <li>Seizures</li>
            </ul>
          </li>
        </ol>

        <h4>What Treatments are Available for Huntington’s Disease?</h4>

        <p>
          At the present moment, there is no cure for Huntington’s disease. However, medications can significantly lessen movement and psychiatric disorders caused by HD. Some medications known to treat Huntington's disease are:

          <ul>
            <li><a href="http://www.xenazineusa.com/">XENAZINE®(Tetrabenazine)</a></li>
            <li><a href="https://www.austedo.com/?utm_content=Brand_Info_Exact&gclid=CjwKEAjwrO_MBRDxgqLa-LX041QSJABgmcMs32g8mwsTX7FHdZXXfx5N7gc2LsusjtSrgCyvlv1cPxoCfGPw_wcB&gclsrc=aw.ds">AUSTEDO™(Deutetrabenazine)</a></li>
          </ul>
        </p>

        <p>
          Along with medicinal assistance, there are diet changes that can be implemented to promote brain health during the at-risk early stages of HD. Eating foods high in vitamin B12, antioxidants, and essential fatty acids can help to nourish the brain. Speech and language therapies are options that assist in alleviating symptoms that affect speech and language.
        </p>

        <p>For more information on Huntington’s disease contact your medical provider.</p>
        <%= link_to "Download A Referral Form", enrollment_path, class: "btn btn-default btnsubmit enrollment-trick" %>
    </div>
</div>

app/views/specialties/_hepb.html.erb
<div class="row">
    <p class="article-no-display">#<%= @article %> .icon</p>
    <div class="col-lg-4 col-md-3 col-sm-7 ">
        <div class="profile-box">
            <%= image_tag "card.png", width: "100%" %>
        </div>
    </div>
    <div class="col-lg-4 col-md-7 col-sm-5  pl-50">
        <h1>HEPATITIS B</h1>
        <br>

        <h4>What is Hepatitis B?</h4>
        <p>Hepatitis B also known as hep B of HBV is a disease affecting the liver that is caused by the hepatitis B virus. Hep B is spread through contact with bodily fluids from an HBV infected person. People can become infected with hepatitis B through sexual intercourse, drug use that includes sharing syringes or other shared paraphernalia equipment, tattoo needles, and items such as razors and toothbrushes.<br>An infected person can experience either acute or chronic hepatitis B. Symptoms from acute HBV can last anywhere between a few weeks to six months. Those who are infected with chronic HBV are those who test positive for the virus for over six months.
        </p>

        <p><b>Symptoms of Hepatitis B include:</b></p>

        <p>
          <ul>
            <li>Dark urine</li>
            <li>Abdominal pain</li>
            <li>Loss of appetite</li>
            <li>Light-colored stools</li>
            <li>Nausea</li>
            <li>Weakness</li>
          </ul>
        </p>

        <p><b>Treatment:</b></p>

        <p>Luckily, for those infected with hepatitis B, there are many specialty medications that can be used to treat a Hep B infection such as:
          <ul>
            <li>VIEKIRA XR™</li>
            <li>MAVYRET™</li>
            <li>VEMLIDY®</li>
            <li>Baraclude®</li>
            <li>EPIVIR-HBV®</li>
            <li>HEPSERA®</li>
            <li>INTRON® A</li>
            <li>PEGASYS®</li>
          </ul>
        </p>

        <p><b>For more information on ways to diagnose and treat an HBV Infection speak with your medical provider.</b></p>

        <%= link_to "Download A Referral Form", enrollment_path, class: "btn btn-default btnsubmit enrollment-trick" %>
    </div>
</div>

app/views/specialties/_it.html.erb
<div class="row">
    <p class="article-no-display">#<%= @article %> .icon</p>
    <div class="col-lg-4 col-md-3 col-sm-7 ">
        <div class="profile-box">
            <%= image_tag "card.png", width: "100%" %>
        </div>
    </div>
    <div class="col-lg-4 col-md-7 col-sm-5  pl-50">
        <h1>INFUSION THERAPY</h1>
        <br>

        <h4>What is Infusion Therapy?</h4>
        <p>Infusion therapy (IV or Intravenous therapy) is an alternative to receiving medication and nutrients orally. Those who are infected with chronic illnesses are sometimes unable to swallow pills that will assist in remedying their disease. Even if an ill individual were able to swallow the necessary medication their stomach acids could destroy the medication rendering it ineffective. In these cases, infusion therapy is the perfect alternative treatment for receiving medication.</p>
        <p>Infusion therapy is when fluids are directly entered into veins through the use of a needle or catheter. IV therapy can be used to treat illness, disease, and deficiencies. The treatment is so reliable that it is often used to treat chronic illnesses. Intravenous therapy is used to treat:</p>
        <br>

        <ul>
          <li><b>Immune Neutropenia:</b> this illness is characterized by the immune system attacking itself and causing the body’s neutrophils count to drop. Neutrophils are a type of white blood cell that attacks invaders of your bodily system such as bacteria. When your neutrophils count drops you become more susceptible to illness and infection.</li>
          <li><b>Alpha-1 Antitrypsin Deficiency:</b> also known as AATD, A1AD, and Genetic emphysema is an inherited deficiency. Those who suffer from AATD have low levels of alpha-1 antitrypsin. Alpha-1 antitrypsin is a protein that is found in the blood. Low levels of this protein cause infection and inflammation of the lungs and liver.</li>
          <li><b>Hemophilia:</b> is a rare bleeding disorder. Those who suffer from hemophilia do not have enough proteins that induce blood clotting. Due to the blood’s inability to clot, hemophiliacs once injured endure prolonged bleeding that can be fatal.</li>
          <li><b>Hepatitis C:</b> if you would like to learn more about Hep C click <%= link_to "HERE", specialties_path( :article => "hepc" ) %></li>
        </ul>

        <p><b>Infusion therapy is also used to treat:</b></p>
          <ul>
            <li>Cancers</li>
            <li>Diseases of the intestines</li>
            <li>Dehydration</li>
            <li>Viral Infections</li>
            <li>Chronic pain</li>
            <li>Vitamin deficiencies</li>
            <li>Arthritis</li>
            <li>Crohn’s disease</li>
            <li>Lupus</li>
            <li>Headaches</li>
          </ul>

        <p>
          IV therapy is so trusted that special practices utilize it to administer vitamins as beauty treatments. Intravenous therapy is a truly versatile therapy that helps in the remedying of many causes of discomfort.
        </p>

        <p>
          <b>Some infusion therapies that deal directly with health are:</b>
          <ul>
            <li>IV Chemotherapy</li>
            <li>Intravenous hydration therapy</li>
            <li>Pain management</li>
            <li>Intravenous anti-coagulation therapy</li>
            <li>Intravenous antibiotic therapy</li>
          </ul>
        </p>

        <p><b>Talk to your doctor about how Infusion therapy can assist you on your way to a perfect bill of health</b></p>

        <%= link_to "Download A Referral Form", enrollment_path, class: "btn btn-default btnsubmit enrollment-trick" %>
    </div>
</div>